# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch102', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
