# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 11:46
from __future__ import unicode_literals

import ch102.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch102', '0004_auto_20180213_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='file1',
            field=models.FileField(null=True, upload_to=ch102.models.file_path_1),
        ),
        migrations.AddField(
            model_name='links',
            name='file2',
            field=models.FileField(null=True, upload_to=ch102.models.file_path_2),
        ),
        migrations.AddField(
            model_name='links',
            name='file3',
            field=models.FileField(null=True, upload_to=ch102.models.file_path_3),
        ),
        migrations.AddField(
            model_name='links',
            name='file4',
            field=models.FileField(null=True, upload_to=ch102.models.file_path_4),
        ),
        migrations.AddField(
            model_name='links',
            name='file5',
            field=models.FileField(null=True, upload_to=ch102.models.file_path_5),
        ),
        migrations.AlterField(
            model_name='links',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('exam', 'exam'), ('quiz', 'quiz'), ('recitation', 'recitation'), ('lecture', 'lecture')], max_length=15),
        ),
    ]
