# Generated by Django 2.0.2 on 2018-02-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch101', '0002_auto_20180213_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('exam', 'exam'), ('quiz', 'quiz'), ('recitation', 'recitation'), ('lecture', 'lecture')], max_length=15),
        ),
    ]
