# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch101', '0004_evaluation_safety'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='Safety',
        ),
    ]
